### ISSUE TITLE
fork해도 될까요??

### ISSUE THREAD

**Issue by rimiiii** [sallyworld/sallyworld.github.io#3]
안녕하세요!
서칭하다가 발견한 블로그인데 테마가 너무 마음에 들어서요!
혹시 실례가 되지 않는다면 fork해가도 될까요??

**Comment by sallyworld** [comment]
안녕하세요.

작업 초기 단계인데 좋게 봐 주셔서 감사합니다. Fork 후 개선할 점 있으면 작업해서 PR 생성해 주셔도 됩니다.

감사합니다. 🙂

나의 iPhone에서 보냄

2021. 2. 2. 14:44, 율링 <notifications@github.com> 작성:

﻿

안녕하세요!
서칭하다가 발견한 블로그인데 테마가 너무 마음에 들어서요!
혹시 실례가 되지 않는다면 fork해가도 될까요??

**Comment by rimiiii** [comment]
감사합니다!😀
